services:
  scraper:
    build: .
    container_name: autoria_scraper
    environment:
      - PG_HOST=${PG_HOST}
      - PG_DBNAME=${PG_DBNAME}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=${PG_PORT:-5432}
      - AUTO_RIA_START_URL=${AUTO_RIA_START_URL:-https://auto.ria.com/uk/car/used/}
      - SCRAPE_TIME=${SCRAPE_TIME:-01:00}
      - DUMP_TIME=${DUMP_TIME:-03:00}
      - AUTO_SCRAPE_TIME=${AUTO_SCRAPE_TIME}
    volumes:
      - ./dumps:/app/dumps
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import psycopg2; psycopg2.connect(host='${PG_HOST}', database='${PG_DBNAME}', user='${PG_USER}', password='${PG_PASSWORD}', port='${PG_PORT:-5432}')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s